### ISSUE TITLE
Double hp regen

### ISSUE THREAD

**Issue by hendogeny** [The-Liam-Blair/Risk-of-Rain-2-RigsArsenal#1]
This mod doubles all characters hp regen, making them heal 2hp per tick instead of one. Not sure if this is intentional or not but it's very strong. If this isn't a bug, could you add a setting to disable it?

**Comment by The-Liam-Blair** [comment]
Hello! I've tracked down that behaviour to the on heal hook for the Worn-Out Stimpack, where it was erroneously calling orig() twice instead of once, so it was a bug.

It's now been fixed and the mod has been updated with this change. Thank you for identifying this bug.
